sudo: false
language: python
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37,mypy,pylint,flake8
    dist: xenial
install: pip install tox
script: tox
deploy:
    provider: pypi
    distributions: "sdist bdist_wheel"
    skip_existing: true
    user: macbeth322
    password:
        secure: "cv5Tb3C3wN4Sif5+9pk6Xgzzko9dftKlbIUKHRb4xV3EjpCH+E6koeLrqOa/Aoh5VwExTLMVQVQUg3x3x0Ks2LETgd7aGmwSzC6gqHjCVkvxwbX6/OIht+b8zCc+I9qaRNk3rb1XLYtEGni8kJK2yJtZa3AgCnu9sVMhbUlp2QZrTNFkKv6hPxKIDK+gZpglfyvjh8+UyHwjv1oy0KvaPdCRCSBKxZsOZfocRckX3BKMorrdyHl/daPnwOMB2pmCGxoYbnUwRusvcROdN4ZidmU32VIRzW7GiQLlcKKheZ2H5t0J0cJ0cKwqSKU4sOyZnl2LJBQGUoA0gWQq0McTyRb35afDimAcde77hRfyPveUmciqTiPTFJa0vwS1ruIquLu5ZoDf6ZhTlReOIaAKhkGZbNYjqQLRcLv+tnkBd8r87elzr8LN0tRiz1XW6qjz8OaeUoDNsycytweuFRsJwZP2IC+F+qatrYCfc2YT6y0Qm1opjwbtyuQiUT2F09Dgohp4n5RqVGytP9ldBHhIdiDhA9q2VXI+3srpZUvBwQYKf+vgvdDIi/TearFbmsre5YWlOB5UtkpC84orNQu24LOeLQpZUhdm8sZJOfBcJ8dT+hD+eTKXKaYlESBRUArQfgvdygIjPGz4JsjoY8LTTTpr+VxKY4PzsEHLxgXPh2k="
