sudo: false
language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV=py36,mypy,pylint,flake8
        - python: 3.7
          env: TOXENV=py37
          dist: xenial
install: pip install tox
script: tox
